### PR TITLE
Migrate from Travis CI to GitHub Actions

### LINKED ISSUE #85: Replace Travis CI with GitHub Actions
Looking at https://travis-ci.org/github/robfig/soy, the last time it ran was over 2 years ago, so this project is currently without automatic testing for new PRs.

Additionally, there's a message at the top of the page:

> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

Would you be open to converting the Travis CI config for this project to GitHub Actions?

Should be pretty straight-forward, happy to help with this. In fact, looking at the history, looks like I made the last change to the [`.travis.yml`](https://github.com/robfig/soy/commits/master/.travis.yml) config file, over 2 years ago now (!) anyway. :-)

### PR DESCRIPTION
**Pull request by mbrukman**
This simply rewrites the Travis CI config format to GitHub Actions, while keeping the same (old) Go versions (but ignoring "tip" since that's too new).

We can incrementally migrate to newer, supported versions of Go after we've validated that this format works with the current Go versions.

Fixes https://github.com/robfig/soy/issues/85

### CODE REVIEW

**Comment by mbrukman** [comment]
@robfig — please enable GitHub Actions on this repo if you haven't already, so that this new config can run.

**Comment by robfig** [comment]
Hm, It looks like it's already enabled, but I don't see a way to run your workflow. Any tips?

image

**Comment by mbrukman** [comment]
> Hm, It looks like it's already enabled, but I don't see a way to run your workflow. Any tips?

Huh, maybe it just doesn't run if it's just being created in this PR? In that case, might as well merge it, and let's see if it passes or fails, and I'll fix it up after it's submitted if needed. I was going to update the list of Go versions anyway.

**Comment by robfig** [comment]
SGTM, thanks

**Comment by mbrukman** [comment]
Looks like it works! Here's the current status (from the [README](https://github.com/robfig/soy/blob/c50f1b6ba73823a8086f546415e613273cc2d1c9/README.md?plain=1#L4)):

[Build Status](https://github.com/robfig/soy/actions/workflows/go.yaml?query=branch%3Amaster)

**Pull request merged**
